name: 'Check for Vulnerabilities'

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # X.X.X - Latest version available at: https://github.com/kunalnagarco/action-cve/releases
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.DEPENDABOT_GH_APP_ID }}
          application_private_key: ${{ secrets.DEPENDABOT_GH_KEY }}
      
      - uses: kunalnagarco/action-cve@v1.14.3
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          slack_webhook: ${{ secrets.DEPENDABOT_SLACK_WEBHOOK }}
          severity: 'high,critical'
          count: 10
